# version: '3.8'

services:
  postgress:
    image: postgres:alpine3.16
    container_name: productos-db
    restart: always
    environment:
      POSTGRES_DB: productosdb
      POSTGRES_USER: productos
      POSTGRES_PASSWORD: productos
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - productos_network

volumes:
  postgres_data:

networks:
  productos_network:
    driver: bridge
